### PR TITLE
Fix/add another

### PR DESCRIPTION
**Pull request by 21adrian1996**
The encapsulation into window onload will not work if the onload method is overwritten later by another package (for example it isn't working properly with django suits).

As document ready seems to be late enough for the method to work properly, I think simply removing it should be a good fix.

### CODE REVIEW

**Comment by 21adrian1996** [comment]
This realtes to https://github.com/deschler/django-modeltranslation/issues/565

**Comment by last-partizan** [comment]
We're not using `window.onload`, we're using `$(window).on("load"`, are you sure it gets overriden by another packages?

You have tested this, and it's working for you?

**Comment by 21adrian1996** [comment]
Not sure if it is overwritten or otherwise not fired, but it does not work properly like this.

I have implemented this fix in one of our projects and it works perfectly also in combination with django-suits.

**Comment by last-partizan** [comment]
Well, let's try and hope it doesn't break something :)

**Pull request merged**
