### PR TITLE
Add django 3.0 to the test matrix

### PR DESCRIPTION
**Pull request by mvbrn**

### CODE REVIEW

**Comment by last-partizan** [comment]
@mvbrn we can not merge this until it passes tests. Can you fix this?

**Comment by last-partizan** [comment]
@mvbrn any news on this?

**Comment by mvbrn** [comment]
Unfortunately, error is not so obvious and probably it's related to some changes in internal mechanics of Django ORM. Have no time to dig into it :/

**Comment by last-partizan** [comment]
I've got some time to look into this. And it was already almost fixed, but hardcoded to use correct code only for django 2, not 3.

Thanks for your contribution :ok_hand:

**Pull request merged**
