### PR TITLE
Fix manager interface type overrides

### LINKED ISSUE #760: TypeError: __class__ assignment: 'NewMultilingualManager' object layout differs from 'SoftDeletableManager'
After upgrading to 5.0, I am getting this error in translated models. 
I am using 
django-model-utils==5.0.0
django-modeltranslation==0.19.9

My model
```
class ParameterModel(UUIDModel, SoftDeletableModelMixin):
    value = models.CharField(verbose_name=_("value"), max_length=255)
    sort_order = models.IntegerField(default=0)
    class Meta:
        verbose_name = _("parameter")
        abstract = True
        
class Currency(ParameterModel):
    default = models.BooleanField(default=False)
    
```

Translation registration:
```
class ParameterTranslationOptions(TranslationOptions):
    fields = ("value",)

translator.register(Currency, ParameterTranslationOptions)

```

Error dump:
`
backend-1            | TypeError: __class__ assignment: 'NewMultilingualManager' object layout differs from 'SoftDeletableManager'                                                                        
backend-1            | /usr/local/lib/python3.12/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
backend-1            |   warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
backend-1            | Traceback (most recent call last):                                                                                                                                                 
backend-1            |   File "/backend/manage.py", line 22, in <module>
backend-1            |     main()                                                                                                                                                                         
backend-1            |   File "/backend/manage.py", line 18, in main                                                                                                                                      
backend-1            |     execute_from_command_line(sys.argv)                                                                                                                                            
backend-1            |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line                                                        
backend-1            |     utility.execute()                                                                                                                                                              
backend-1            |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute                                                                          
backend-1            |     django.setup()                                                                                                                                                                 
backend-1            |   File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup                                                                                             
backend-1            |     apps.populate(settings.INSTALLED_APPS)                                                                                                                                         
backend-1            |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate                                                                                    
backend-1            |     app_config.ready()                                                                                                                                                             
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/apps.py", line 11, in ready                                                                                       
backend-1            |     handle_translation_registrations()                                                                                                                                             
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/models.py", line 82, in handle_translation_registrations                                                          
backend-1            |     autodiscover()                                                                                                                                                                 
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/models.py", line 28, in autodiscover                                                                              
backend-1            |     import_module(module)                                                                                                                                                          
backend-1            |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                                                                
backend-1            |     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                    
backend-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                    
backend-1            |   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import                                                                                                                  
backend-1            |   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load                                                                                                               
backend-1            |   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked                                                                                                      
backend-1            |   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked                                                                                                                
backend-1            |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
backend-1            |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
backend-1            |   File "/backend/common/translation.py", line 24, in <module>
backend-1            |     translator.register(Currency, ParameterTranslationOptions)
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/translator.py", line 529, in register
backend-1            |     self._register_single_model(model, opts)
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/translator.py", line 559, in _register_single_model
backend-1            |     add_manager(model)
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/translator.py", line 281, in add_manager
backend-1            |     patch_manager_class(current_manager)
backend-1            |   File "/usr/local/lib/python3.12/site-packages/modeltranslation/translator.py", line 263, in patch_manager_class
backend-1            |     manager.__class__ = NewMultilingualManager
backend-1            |     ^^^^^^^^^^^^^^^^^
backend-1            | TypeError: __class__ assignment: 'NewMultilingualManager' object layout differs from 'SoftDeletableManager'
`

### PR DESCRIPTION
**Pull request by shosca**
Fixes return type overrides of `MultilingualManager.get_queryset` and `MultilingualQuerysetManager.get_queryset`

fixes #760

### CODE REVIEW

**Comment by last-partizan** [comment]
Are you sure it fixes it?

I have tried with `django-model-utils==5.0.0` and issues still exists.

I added a test into master, you can use:

```
pytest modeltranslation/tests/test_compat.py -v
```

Make sure to have latest django-model-utils installed in venv. Old versions does not have this bug.

**Comment by shosca** [comment]
We don't use `django-model-utils` but our situaton is similar in that we have our own flavor of `SoftDeleteManager` where `get_queryset()` is declared as
```python
    def get_queryset(self) -> models.QuerySet[TModel]:
        ....
```
and i think `django-model-utils` suffers the same issue of overloading the return type as well:  https://github.com/jazzband/django-model-utils/blob/d1eb8004f2ebe7524c4de6da9960cd48788953c3/model_utils/managers.py#L398

Our mypy issue with latest `django-modeltranslation` is basically the same error `error: Definition of "get_queryset" in base class "SoftDeleteManager" is incompatible with definition in base class "MultilingualManager"` which is happening because of the return type overload on `get_queryset()` and gets resolved once the return type is set as `Queryset[TModel]`

**Comment by last-partizan** [comment]
Can you show all related code?

`MultilingualManager` is supposed to be completely transparent to the end-user app code.

**Comment by shosca** [comment]
> Can you show all related code?
> 
> `MultilingualManager` is supposed to be completely transparent to the end-user app code.

Sure, i've created a repo that reproduces our mypy issues here: https://github.com/shosca/repro_761

**Comment by last-partizan** [comment]
In that repo, you're using `django-model-utils`, and you said earlier you don't use it.

You don't need to subclass `MultilingualManager` in your app code, just remove it and django-modeltranslation takes care of the rest.

If you really need to subclass it, then - add `# type: ignore` comment for that line.

**Pull request closed without merging**
